<?php

declare(strict_types=1);

namespace PHPLLM\Tests\Unit;

use PHPLLM\Core\Tool;
use PHPLLM\Tests\TestCase;

class GetWeatherTool extends Tool
{
    protected string $name = 'get_weather';
    protected string $description = 'Get weather for a location';

    protected function parameters(): array
    {
        return [
            'location' => [
                'type' => 'string',
                'description' => 'City name',
                'required' => true,
            ],
            'unit' => [
                'type' => 'string',
                'enum' => ['celsius', 'fahrenheit'],
            ],
        ];
    }

    public function execute(array $arguments): mixed
    {
        return [
            'location' => $arguments['location'],
            'temperature' => 22,
            'unit' => $arguments['unit'] ?? 'celsius',
        ];
    }
}

class ToolTest extends TestCase
{
    public function testToolName(): void
    {
        $tool = new GetWeatherTool();
        $this->assertEquals('get_weather', $tool->getName());
    }

    public function testToolDescription(): void
    {
        $tool = new GetWeatherTool();
        $this->assertEquals('Get weather for a location', $tool->getDescription());
    }

    public function testToolParameters(): void
    {
        $tool = new GetWeatherTool();
        $params = $tool->getParameters();

        $this->assertEquals('object', $params['type']);
        $this->assertArrayHasKey('location', $params['properties']);
        $this->assertContains('location', $params['required']);
    }

    public function testToolExecution(): void
    {
        $tool = new GetWeatherTool();
        $result = $tool->execute(['location' => 'Tokyo', 'unit' => 'celsius']);

        $this->assertEquals('Tokyo', $result['location']);
        $this->assertEquals(22, $result['temperature']);
        $this->assertEquals('celsius', $result['unit']);
    }

    public function testToFunctionSchema(): void
    {
        $tool = new GetWeatherTool();
        $schema = $tool->toFunctionSchema();

        $this->assertEquals('function', $schema['type']);
        $this->assertEquals('get_weather', $schema['function']['name']);
        $this->assertEquals('Get weather for a location', $schema['function']['description']);
    }

    public function testAutoGeneratedName(): void
    {
        $tool = new class () extends Tool {
            protected string $description = 'Test tool';

            public function execute(array $arguments): mixed
            {
                return null;
            }
        };

        // Anonymous classes get weird names, but real classes would get snake_case
        $this->assertNotEmpty($tool->getName());
    }
}
